# Generated by Django 3.1.7 on 2021-03-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                #('phone', models.IntegerField()),
                ('gradYear', models.DateField()),
                ('company', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='uProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userid')),
            ],
        ),
        migrations.CreateModel(
            name='uBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetMe', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=50)),
                ('minor', models.CharField(max_length=50)),
                ('aInterest', models.TextField()),
                ('aExpertise', models.TextField()),
                ('rGoal', models.TextField()),
                ('bPic', models.ImageField(height_field='396', upload_to='', width_field='1584')),
                ('uPic', models.ImageField(height_field='320', upload_to='', width_field='320')),
                ('curLooking', models.TextField()),
                ('twitter', models.CharField(max_length=30)),
                ('insta', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=30)),
                ('linkedin', models.CharField(max_length=30)),
                ('tictok', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userid')),
            ],
        ),
    ]
